version: 2

models:
  - name: stg_customers
    description: "List customer "
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: first_name
        tests:
          - not_null
      - name: last_name
        tests:
          - not_null
  - name: stg_orders
    description: "List order"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
  - name: stg_payments
    columns:
      - name: payment_id
        test: 
          - not_null
          - unique
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']